@echo off
:: ========================================

:: find root dir
for /f "delims=" %%i in ("%~dp0") do (
  set "MY_ROOT=%%~fi"
)
:: remove trailing '\' from %MY_ROOT%
if "%MY_ROOT:~-1%" == "\" set "MY_ROOT=%MY_ROOT:~0,-1%"

set "MY_SETTINGS=%MY_ROOT%\settings"

:: config alacritty
:: ========================================

:: create alacritty directory
if not exist "%APPDATA%\alacritty" (
  mkdir "%APPDATA%\alacritty"
)

set "MY_SETTINGS_ESCAPED=%MY_SETTINGS:\=\\%"

:: generate alacritty.toml
(
echo # this file is auto-generated by github.com/jwu/alacritty-settings
echo [general]
echo import = ["%MY_SETTINGS_ESCAPED%\\alacritty.toml"]
echo.
echo [terminal]
echo [terminal.shell]
echo program = "cmd.exe"
echo args = ["/s", "/k", "%MY_SETTINGS_ESCAPED%\\init.bat"]
echo.
echo # this will fix OpenCode not work with IME problem
echo [mouse]
echo hide_when_typing = true
) > %APPDATA%\alacritty\alacritty.toml
