@echo off
:: ========================================

:: find root dir
for /f "delims=" %%i in ("%~dp0") do (
  set "MY_ROOT=%%~fi"
)
:: remove trailing '\' from %MY_ROOT%
if "%MY_ROOT:~-1%" == "\" set "MY_ROOT=%MY_ROOT:~0,-1%"

set "MY_SETTINGS=%MY_ROOT%\settings"

:: config alacritty
:: ========================================

:: create alacritty directory
if not exist "%APPDATA%\alacritty" (
  mkdir "%APPDATA%\alacritty"
)

:: generate alacritty.toml
@echo off
(
echo # this file is auto-generated by github.com/jwu/alacritty-settings
echo import = ['%MY_SETTINGS%\alacritty.toml']
echo
echo [shell]
echo program = "cmd.exe"
echo args = ['/s /k "%MY_SETTINGS%\init.bat"']
) > %APPDATA%\alacritty\alacritty.toml
