:: find root dir
for /f "delims=" %%i in ("%~dp0\..") do (
  set "AL_ROOT=%%~fi"
)
:: remove trailing '\' from %AL_ROOT%
if "%AL_ROOT:~-1%" == "\" set "AL_ROOT=%AL_ROOT:~0,-1%"

set "AL_SETTINGS=%AL_ROOT%\settings"
set "AL_VENDOR=%AL_ROOT%\vendor"

:: install alacritty
:: ========================================

:: download alacritty.exe
curl -L -o alacritty.exe https://github.com/alacritty/alacritty/releases/download/v0.11.0/Alacritty-v0.11.0-portable.exe

:: create alacritty directory
if not exist "%APPDATA%\alacritty" (
  mkdir "%APPDATA%\alacritty"
)

:: generate alacritty.yml
@echo off
(
echo # this file is auto-generated by github.com/jwu/alacritty-settings
echo import:
echo   - %AL_SETTINGS%\alacritty.yml
echo shell:
echo   program: cmd.exe
echo   args:
echo     - /s /k "%AL_SETTINGS%\init.bat"
) > %APPDATA%\alacritty\alacritty.yml

:: create vendor directory
:: ========================================

if not exist "%AL_VENDOR%" (
  mkdir "%AL_VENDOR%"
)

:: install nerdfonts FiraMono
:: ========================================

:: install git-for-windows
:: ========================================
