# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold cyan"

[package]
disabled = true

[git_branch]
always_show_remote = true
symbol = " "
style = "bold purple"
format = "on [$symbol$branch -> $remote_name]($style) "

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
style = "bold yellow"
untracked = ""
modified = '*'
deleted = '-'
conflicted = 'x'
ahead = "[\ue353${count}](bold green)"
behind = "[\ue340${count}](bold red)"
diverged = "[⇕\ue353${ahead_count}\ue340${behind_count}](bold yellow)"
format = '([\[$conflicted$stashed$deleted$renamed$staged$modified\]]($style) $ahead_behind )'
