@echo off
:: ========================================

:: find settings dir (current script dir)
for /f "delims=" %%i in ("%~dp0") do (
  set "MY_SETTINGS=%%~fi"
)
:: remove trailing '\' from %MY_SETTINGS%
if "%MY_SETTINGS:~-1%" == "\" set "MY_SETTINGS=%MY_SETTINGS:~0,-1%"

:: find root dir (parent of settings dir)
for /f "delims=" %%i in ("%MY_SETTINGS%\..") do (
  set "MY_ROOT=%%~fi"
)

:: config alacritty
:: ========================================

:: create alacritty directory
if not exist "%APPDATA%\alacritty" (
  mkdir "%APPDATA%\alacritty"
)

set "MY_SETTINGS_ESCAPED=%MY_SETTINGS:\=\\%"
set "MY_ROOT_ESCAPED=%MY_ROOT:\=\\%"

:: generate alacritty.toml
(
echo # this file is auto-generated by github.com/jwu/settings
echo [general]
echo import = ["%MY_SETTINGS_ESCAPED%\\alacritty.toml"]
echo.
echo [terminal]
echo [terminal.shell]
echo program = "cmd.exe"
echo args = ["/s", "/k", "%MY_SETTINGS_ESCAPED%\\init.bat"]
) > %APPDATA%\alacritty\alacritty.toml

:: config lsd
:: ========================================

:: create lsd directory
if not exist "%APPDATA%\lsd" (
  mkdir "%APPDATA%\lsd"
)

:: generate config.yaml
(
echo # this file is auto-generated by github.com/jwu/settings
echo source: "%MY_ROOT_ESCAPED%\\common\\lsd.yaml"
) > "%APPDATA%\lsd\config.yaml"

:: config neovim
:: ========================================

:: create nvim directory
if not exist "%LOCALAPPDATA%\nvim" (
  mkdir "%LOCALAPPDATA%\nvim"
)

:: generate init.lua
(
echo -- this file is auto-generated by github.com/jwu/settings
echo dofile^("%MY_ROOT_ESCAPED%\\common\\neovim.init.lua"^)
) > "%LOCALAPPDATA%\nvim\init.lua"

:: config neovide
:: ========================================

:: create neovide directory
if not exist "%APPDATA%\neovide" (
  mkdir "%APPDATA%\neovide"
)

:: generate config.toml
(
echo # this file is auto-generated by github.com/jwu/settings
echo include "%MY_ROOT_ESCAPED%\\common\\neovide.config.toml"
) > "%APPDATA%\neovide\config.toml"

:: config omnisharp
:: ========================================

:: create omnisharp directory
if not exist "%USERPROFILE%\.omnisharp" (
  mkdir "%USERPROFILE%\.omnisharp"
)

:: copy omnisharp.json
copy /Y "%MY_ROOT%\common\omnisharp.json" "%USERPROFILE%\.omnisharp\omnisharp.json"

:: config zed
:: ========================================

:: create zed directory
if not exist "%APPDATA%\zed" (
  mkdir "%APPDATA%\zed"
)

:: copy zed settings
copy /Y "%MY_ROOT%\common\zed.settings.json" "%APPDATA%\zed\settings.json"

:: config wezterm
:: ========================================

:: generate .wezterm.lua
(
echo -- this file is auto-generated by github.com/jwu/settings
echo local config = dofile^("%MY_ROOT_ESCAPED%\\common\\wezterm.lua"^)
echo.
echo config.default_prog = { 'cmd.exe', '/s', '/k', '%MY_SETTINGS_ESCAPED%\\init.bat' }
echo.
echo return config
) > "%USERPROFILE%\.wezterm.lua"
